---
title: "432 Main Page for Spring 2023"
date: last-modified
---

## Welcome! 

PQHS/CRSP/MPHP 432 is the second half ([431 is the first half](https://thomaselove.github.io/431-2022/)) of a two-semester course taught by Professor Thomas Love in the Department of Population and Quantitative Health Sciences at Case Western Reserve University. 

If you have any questions before class begins, contact Dr. Love at `Thomas dot Love at case dot edu`.

## Everything will appear here.

Everything that Professor Love will provide to help you with the course will be linked through this website. The menu bar links to just about everything you'll need this semester, and its elements will go live as they become available. Things you'll find here include...

- The [Course Calendar](calendar.qmd), which includes links to class materials, assignments and other information, and which is the final word on all deadlines for the course.
- The [Course Syllabus](syllabus.qmd) for 432.
- Professor Love's [Course Notes](notes.qmd) for 432.
- Details on Assignments, including [Projects](projA.qmd), [Quizzes](quiz1.qmd), [Labs](lab1.qmd) and [Minute Papers](https://github.com/THOMASELOVE/432-minute-2023)
- Information on installing R and RStudio [software](software.qmd), installing key [R packages](software.qmd#r-packages-to-install), and [downloading data, code and templates](https://github.com/THOMASELOVE/432-data) you'll need for this class
- Important Links to other systems that will help us deliver 432, including:
    - the [Canvas system](https://canvas.case.edu/) (CWRU log-in required) we use to communicate information about class recordings, and for turning in assignments
    - our Shared Google Drive ([432 Spring 2023 Dr Love and Students](https://docs.google.com/document/d/1A6-P4TRXrCZVAqfDWw_s75lBGID9wHiaJjbsjltXojs/edit?usp=sharing)) (CWRU log-in required) where we provide answer sketches for class assignments, an in-semester grading roster, and feedback on Minute Papers
    - the [Campuswire discussion board](https://campuswire.com/) for the 432 course
- Information on places where you can [get help and contact us](contact.qmd) once the course begins.
- Additional Sources and references, including things to read or watch to supplement our main work

## Accessing the 431 Materials

Note that the [431 class materials from Fall 2022 are here](https://thomaselove.github.io/431-2022/), and will remain there until 2023-06-01.

